msg="\n\n\#\#\n\#\#\n\#\# This file was generated by a script. Don't edit it.\n\#\#\n\#\#"



# 1. Create new targets for your executables
# 2. Modify pt-sim.sh and pt-sim-clock.sh
#    so it calls the appropriate executable
# 3. Include the relevant target in the list
#    of dependencies for each of pt-sim
#    and pt-sim-aging

all: ptsim ptsim-clock

ptsim:
	echo "#!/bin/bash" > ptsim
	echo "python3 ptsim.py \$$1" >> ptsim
	chmod +x ptsim

ptsim-clock:
	echo "#!/bin/bash" > ptsim-clock
	echo "python3 ptsim_clock.py \$$1" >> ptsim-clock
	chmod +x ptsim-clock

clean:
	rm -f ptsim ptsim-clock
